
name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install symd
      run: |
        sudo apt-get install libgsl-dev cmake  libxml2-dev libxslt1-dev
        mkdir build && cd build && cmake .. && make && sudo make install
    - name: Install dependencies
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Install
      working-directory: python
      run: |
        pip install . && pip install -r docs/requirements.txt
    - name: Sphinx build
      working-directory: python/docs
      run: |
        cp ../../notebooks/*ipynb source
        make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: python/docs/build/html
