
name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install symd
      run: |
        sudo apt-get install libgsl-dev cmake
        mkdir build && cd build && cmake .. && make && sudo make install
    - name: Install dependencies
      working-directory: python
      run: |
        python -m pip install --upgrade pip
        if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
    - name: Install
      working-directory: python
      run: |
        pip install . && pip install -r docs/requirements.txt
    - name: Run tests
      working-directory: python
      run: |
        pytest